import React, { useState, useEffect } from "react";
import {
  Brain,
  Languages,
  Copy,
  Volume2,
  History,
  Star,
  MessageSquare,
  Download,
  Sparkles,
} from "lucide-react";
import ApiService from "../../services/api";
import LocalStorageService, {
  MedicalExplanation,
} from "../../services/localStorage";
import toast from "react-hot-toast";

interface MedicalExplainerProps {
  compact?: boolean;
}

const MedicalExplainer: React.FC<MedicalExplainerProps> = ({
  compact = false,
}) => {
  const [inputText, setInputText] = useState("");
  const [language, setLanguage] = useState("english");
  const [explaining, setExplaining] = useState(false);
  const [currentExplanation, setCurrentExplanation] = useState<any>(null);
  const [history, setHistory] = useState<MedicalExplanation[]>([]);
  const [aiStatus, setAiStatus] = useState<"online" | "offline">("online");

  useEffect(() => {
    loadHistory();
    checkAIStatus();
  }, []);

  const loadHistory = () => {
    const explanations = LocalStorageService.getExplanations();
    setHistory(explanations.slice(0, 10));
  };

  const checkAIStatus = async () => {
    try {
      const health = await ApiService.checkHealth();
      setAiStatus(health.status === "healthy" ? "online" : "offline");
    } catch {
      setAiStatus("offline");
    }
  };

  const exampleQueries = [
    { text: "What is hypertension?", icon: "🫀" },
    { text: "Explain myocardial infarction", icon: "❤️" },
    { text: "What does high cholesterol mean?", icon: "🩸" },
    { text: "How does metformin work?", icon: "💊" },
    { text: "What is Type 2 Diabetes?", icon: "🩺" },
    { text: "Explain insulin resistance", icon: "🔬" },
  ];

  const handleExplain = async () => {
    if (!inputText.trim()) {
      toast.error("Please enter medical text to explain");
      return;
    }

    setExplaining(true);
    try {
      const explanation = await ApiService.explainMedicalText(
        inputText,
        language
      );
      setCurrentExplanation(explanation);

      // Save to history
      const medicalExplanation: MedicalExplanation = {
        id: Date.now().toString(),
        originalText: explanation.original,
        explanation: explanation.explanation,
        language: explanation.language,
        timestamp: explanation.timestamp,
        confidence: explanation.confidence,
      };

      LocalStorageService.saveExplanation(medicalExplanation);
      setHistory((prev) => [medicalExplanation, ...prev]);

      toast.success("AI explained successfully!", {
        icon: "🧠",
      });
    } catch (error: any) {
      toast.error(error.response?.data?.detail || "AI service unavailable");
      // Fallback
      setCurrentExplanation({
        original: inputText,
        explanation: `"${inputText}" refers to a medical concept. In simple terms, this is something you should discuss with your doctor for personalized advice.`,
        confidence: "low",
        language,
        timestamp: new Date().toISOString(),
      });
    } finally {
      setExplaining(false);
    }
  };

  const handleExplainDiagnosis = async () => {
    const diagnosis = inputText;
    const notes = prompt("Add any additional notes from your doctor:") || "";

    setExplaining(true);
    try {
      const explanation = await ApiService.explainDiagnosis(diagnosis, notes);
      setCurrentExplanation({
        ...explanation,
        type: "diagnosis",
      });
      toast.success("Diagnosis explained!", { icon: "🩺" });
    } catch (error) {
      toast.error("Error explaining diagnosis");
    } finally {
      setExplaining(false);
    }
  };

  const handleCopy = () => {
    if (currentExplanation?.explanation) {
      navigator.clipboard.writeText(currentExplanation.explanation);
      toast.success("Copied to clipboard!");
    }
  };

  const handleSpeak = () => {
    if (currentExplanation?.explanation && "speechSynthesis" in window) {
      const speech = new SpeechSynthesisUtterance(
        currentExplanation.explanation
      );
      speech.lang =
        language === "isizulu"
          ? "zu"
          : language === "afrikaans"
          ? "af"
          : "en-US";
      speech.rate = 0.9;
      window.speechSynthesis.speak(speech);
    }
  };

  const handleDownload = () => {
    if (!currentExplanation) return;

    const content = `
Medical Explanation
===================

Original: ${currentExplanation.original}
Explanation: ${currentExplanation.explanation}
Language: ${currentExplanation.language}
Confidence: ${currentExplanation.confidence}
Date: ${new Date(currentExplanation.timestamp).toLocaleString()}

Generated by Mediclinic AI with Llama 3.2
    `;

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `medical-explanation-${Date.now()}.txt`;
    a.click();
    toast.success("Downloaded!");
  };

  if (compact) {
    return (
      <div className="medical-card">
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-lg font-bold text-gray-900 flex items-center gap-2">
            <Brain className="w-5 h-5 text-primary-600" />
            AI Medical Explainer
          </h3>
          <span
            className={`badge ${
              aiStatus === "online" ? "badge-success" : "badge-critical"
            }`}>
            {aiStatus === "online" ? "AI Online" : "AI Offline"}
          </span>
        </div>

        <div className="space-y-3">
          <textarea
            value={inputText}
            onChange={(e) => setInputText(e.target.value)}
            placeholder="Ask about any medical term..."
            className="input-field h-32 resize-none"
            rows={3}
          />

          <div className="flex items-center gap-2">
            <select
              value={language}
              onChange={(e) => setLanguage(e.target.value)}
              className="input-field py-2 text-sm flex-1">
              <option value="english">🇺🇸 English</option>
              <option value="isizulu">🇿🇦 isiZulu</option>
              <option value="afrikaans">🇿🇦 Afrikaans</option>
            </select>

            <button
              onClick={handleExplain}
              disabled={explaining || !inputText.trim()}
              className="btn-primary px-4 py-2.5">
              {explaining ? "Explaining..." : "Explain"}
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="medical-card">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <h1 className="text-2xl font-bold text-gray-900 flex items-center gap-3">
              <div className="w-12 h-12 bg-gradient-to-br from-primary-500 to-primary-700 rounded-xl flex items-center justify-center">
                <Brain className="w-6 h-6 text-white" />
              </div>
              <span>AI Medical Explainer</span>
            </h1>
            <p className="text-gray-600 mt-2">
              Powered by Llama 3.2 11B. Get simple explanations of complex
              medical terms.
            </p>
          </div>

          <div className="flex items-center gap-3">
            <div
              className={`badge ${
                aiStatus === "online" ? "badge-success" : "badge-critical"
              } px-4 py-1.5`}>
              <Sparkles className="w-4 h-4 mr-1" />
              {aiStatus === "online" ? "Llama 3.2 Active" : "AI Offline"}
            </div>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Column: Input & Examples */}
        <div className="lg:col-span-2 space-y-6">
          {/* Input Section */}
          <div className="medical-card">
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-xl font-bold text-gray-900 flex items-center gap-2">
                <MessageSquare className="w-5 h-5 text-primary-600" />
                Ask the AI Doctor
              </h2>
              <div className="flex items-center gap-2">
                <Languages className="w-5 h-5 text-gray-500" />
                <select
                  value={language}
                  onChange={(e) => setLanguage(e.target.value)}
                  className="bg-gray-50 border border-gray-300 rounded-lg px-3 py-1.5 text-sm">
                  <option value="english">🇺🇸 English</option>
                  <option value="isizulu">🇿🇦 isiZulu</option>
                  <option value="afrikaans">🇿🇦 Afrikaans</option>
                </select>
              </div>
            </div>

            <textarea
              value={inputText}
              onChange={(e) => setInputText(e.target.value)}
              placeholder="Paste medical text, doctor's notes, or ask about symptoms..."
              className="input-field h-48 resize-none"
              rows={6}
            />

            <div className="flex flex-wrap gap-3 mt-6">
              <button
                onClick={handleExplain}
                disabled={explaining || !inputText.trim()}
                className="btn-primary flex items-center gap-2 px-6">
                {explaining ? (
                  <>
                    <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                    Processing...
                  </>
                ) : (
                  <>
                    <Brain className="w-5 h-5" />
                    Explain with AI
                  </>
                )}
              </button>

              <button
                onClick={handleExplainDiagnosis}
                disabled={explaining || !inputText.trim()}
                className="btn-secondary flex items-center gap-2 px-6">
                <span className="text-lg">🩺</span>
                Explain Diagnosis
              </button>
            </div>
          </div>

          {/* Example Queries */}
          <div className="medical-card">
            <h3 className="text-lg font-bold text-gray-900 mb-4 flex items-center gap-2">
              <Star className="w-5 h-5 text-medical-orange" />
              Try These Examples
            </h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {exampleQueries.map((example, index) => (
                <button
                  key={index}
                  onClick={() => setInputText(example.text)}
                  className="text-left p-4 bg-gray-50 hover:bg-gray-100 rounded-xl transition-all border border-gray-200 hover:border-primary-300 group">
                  <div className="flex items-center gap-3">
                    <span className="text-2xl">{example.icon}</span>
                    <div>
                      <div className="font-medium text-gray-800 group-hover:text-primary-700">
                        {example.text}
                      </div>
                      <div className="text-sm text-gray-500 mt-1">
                        Click to try
                      </div>
                    </div>
                  </div>
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Right Column: History */}
        <div className="space-y-6">
          <div className="medical-card">
            <h3 className="text-lg font-bold text-gray-900 mb-4 flex items-center gap-2">
              <History className="w-5 h-5 text-primary-600" />
              Recent Explanations
            </h3>
            <div className="space-y-3 max-h-96 overflow-y-auto pr-2">
              {history.length > 0 ? (
                <>
                  {history.map((item) => (
                    <div
                      key={item.id}
                      onClick={() =>
                        setCurrentExplanation({
                          original: item.originalText,
                          explanation: item.explanation,
                          language: item.language,
                          timestamp: item.timestamp,
                          confidence: item.confidence,
                        })
                      }
                      className="p-3 bg-gray-50 rounded-xl cursor-pointer hover:bg-gray-100 transition-colors border border-transparent hover:border-gray-200">
                      <div className="font-medium text-gray-800 line-clamp-2">
                        {item.originalText}
                      </div>
                      <div className="flex items-center justify-between mt-2">
                        <span
                          className={`text-xs px-2 py-1 rounded-full ${
                            item.confidence === "high"
                              ? "badge-success"
                              : item.confidence === "medium"
                              ? "badge-warning"
                              : "badge-critical"
                          }`}>
                          {item.confidence}
                        </span>
                        <span className="text-xs text-gray-500">
                          {new Date(item.timestamp).toLocaleDateString()}
                        </span>
                      </div>
                    </div>
                  ))}
                </>
              ) : (
                <div className="text-center py-8 text-gray-500">
                  <MessageSquare className="w-12 h-12 mx-auto mb-3 text-gray-300" />
                  <p>No explanations yet</p>
                  <p className="text-sm mt-1">
                    Your explanations will appear here
                  </p>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* Current Explanation Display */}
      {currentExplanation && (
        <div className="medical-card animate-fade-in">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between mb-6 gap-4">
            <div>
              <h2 className="text-xl font-bold text-gray-900">
                AI Explanation
              </h2>
              <p className="text-gray-600 text-sm mt-1">
                Generated with Llama 3.2 • {currentExplanation.language}
              </p>
            </div>

            <div className="flex items-center gap-2">
              <div
                className={`badge ${
                  currentExplanation.confidence === "high"
                    ? "badge-success"
                    : currentExplanation.confidence === "medium"
                    ? "badge-warning"
                    : "badge-critical"
                } px-3`}>
                {currentExplanation.confidence} confidence
              </div>

              <div className="flex items-center gap-1">
                <button
                  onClick={handleCopy}
                  className="p-2 text-gray-600 hover:text-gray-900 rounded-lg hover:bg-gray-100"
                  title="Copy explanation">
                  <Copy className="w-5 h-5" />
                </button>
                <button
                  onClick={handleSpeak}
                  className="p-2 text-gray-600 hover:text-gray-900 rounded-lg hover:bg-gray-100"
                  title="Read aloud">
                  <Volume2 className="w-5 h-5" />
                </button>
                <button
                  onClick={handleDownload}
                  className="p-2 text-gray-600 hover:text-gray-900 rounded-lg hover:bg-gray-100"
                  title="Download">
                  <Download className="w-5 h-5" />
                </button>
              </div>
            </div>
          </div>

          {/* Original Text */}
          <div className="mb-6 p-4 bg-gray-50 rounded-xl border border-gray-200">
            <div className="text-sm font-medium text-gray-500 mb-2">
              Original Text
            </div>
            <div className="text-gray-800">{currentExplanation.original}</div>
          </div>

          {/* AI Explanation */}
          <div className="p-6 bg-gradient-to-br from-primary-50 to-blue-50 rounded-2xl border border-primary-100">
            <div className="text-sm font-medium text-primary-700 mb-3 flex items-center gap-2">
              <Brain className="w-4 h-4" />
              AI Explanation in Simple Terms
            </div>
            <div className="text-gray-800 leading-relaxed whitespace-pre-line">
              {currentExplanation.explanation}
            </div>

            {currentExplanation.type === "diagnosis" && (
              <div className="mt-6 p-4 bg-white rounded-xl border border-gray-200">
                <div className="text-sm font-medium text-gray-700 mb-2">
                  📋 Diagnosis Summary
                </div>
                <div className="text-gray-600 text-sm">
                  This explanation helps you understand your diagnosis better.
                  Always consult with your healthcare provider for personalized
                  medical advice.
                </div>
              </div>
            )}
          </div>

          {/* Model Info */}
          <div className="mt-6 pt-6 border-t border-gray-200">
            <div className="flex items-center justify-between text-sm text-gray-500">
              <div className="flex items-center gap-2">
                <div className="w-2 h-2 bg-primary-500 rounded-full animate-pulse"></div>
                <span>Generated with Llama 3.2 11B</span>
              </div>
              <div>
                {new Date(currentExplanation.timestamp).toLocaleString()}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default MedicalExplainer;
